name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use a Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: test # This job will only run if the 'test' job passes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy on push to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0 
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # GitHub's automatically provided token
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDDINGBETS }}' # Your Firebase service account secret
          projectId: weddingbets-35d91 # Your Firebase Project ID
          channelId: live # Deploy to the 'live' channel (your main site)
